# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CareConnectFamily' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CareConnectFamily
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'

  target 'CareConnectFamilyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CareConnectFamilyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
