# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CareConnectFamily' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CareConnectFamily
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
pod 'SwiftCharts', '~> 0.6.5'

  target 'CareConnectFamilyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CareConnectFamilyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['SwiftCharts'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end

end
